# Generated by Django 5.1.3 on 2025-01-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empdetails',
            table='EmpDetails',
        ),
    ]
