# Generated by Django 5.1.3 on 2025-01-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_album_author_books_vehicle_personaldata_song_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_city', models.CharField(max_length=255)),
                ('emp_company', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'first_app_empdetails',
            },
        ),
    ]
